# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  num_compute_nodes = (ENV['DEVSTACK_NUM_COMPUTE_NODES'] || 1).to_i

  control_ip = "192.168.50.20"
  compute_ip_base = "192.168.50."
  neutron_ex_ip = "192.168.111.10"
  compute_ex_ip_base = "192.168.111."
  compute_ips = num_compute_nodes.times.collect { |n| compute_ip_base + "#{n+21}" }
  compute_ex_ips = num_compute_nodes.times.collect { |n| compute_ex_ip_base + "#{n+11}" }
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  # Devstack Controller
  config.vm.define "devstack-control", primary: true do |control|
    control.vm.box = "ubuntu/trusty64"
    control.vm.hostname = "devstack-control"
    control.vm.network "private_network", ip: "#{control_ip}"
    control.vm.network "private_network", ip: "#{neutron_ex_ip}", virtualbox__intnet: "mylocalnet", auto_config: false
    control.vm.provider :virtualbox do |vb|
      vb.cpus = 4
      vb.customize ["modifyvm", :id, "--memory", "8192"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype3", "virtio"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    end
    control.vm.provider :libvirt do |v|
      v.memory = 8192
      v.cpus = 4
    end
    control.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook_control.yml"
    end
  end

  num_compute_nodes.times do |n|
    config.vm.define "devstack-compute-#{n+1}", autostart: true do |compute|
      compute_ip = compute_ips[n]
      compute_ex_ip = compute_ex_ips[n]
      compute_index = n+1
      compute.vm.box = "ubuntu/trusty64"
      compute.vm.hostname = "devstack-compute-#{compute_index}"
      compute.vm.network "private_network", ip: "#{compute_ip}"
      compute.vm.network "private_network", ip: "#{compute_ex_ip}", virtualbox__intnet: "mylocalnet", auto_config: false
      compute.vm.provider :virtualbox do |vb|
        vb.cpus = 4
        vb.customize ["modifyvm", :id, "--memory", "8192"]
        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
        vb.customize ["modifyvm", :id, "--nictype3", "virtio"]
        vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      end
      compute.vm.provider :libvirt do |v|
        v.memory = 8192
        v.cpus = 4
        v.nested = true
      end
      compute.vm.provision :ansible do |ansible|
        ansible.playbook = "playbook_compute.yml"
      end
    end
  end
end
